# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nested.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nested.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cnested.proto\"\xf0\x04\n\tFieldInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.FieldType\x12\x13\n\x0b\x65mpty_count\x18\x04 \x01(\x05\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\x12\x30\n\rinteger_stats\x18\x64 \x01(\x0b\x32\x17.FieldInfo.IntegerStatsH\x00\x12\x37\n\x11real_number_stats\x18\x65 \x01(\x0b\x32\x1a.FieldInfo.RealNumberStatsH\x00\x12*\n\ndate_stats\x18\x66 \x01(\x0b\x32\x14.FieldInfo.DateStatsH\x00\x12\x38\n\x11\x63\x61tegorical_stats\x18g \x01(\x0b\x32\x1b.FieldInfo.CategoricalStatsH\x00\x1aZ\n\x0cIntegerStats\x12\x0b\n\x03min\x18\x01 \x01(\x03\x12\x0b\n\x03max\x18\x02 \x01(\x03\x12\x0c\n\x04mean\x18\x03 \x01(\x03\x12\x0e\n\x06median\x18\x04 \x01(\x03\x12\x12\n\npercentile\x18\x05 \x03(\x01\x1a]\n\x0fRealNumberStats\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x12\x0c\n\x04mean\x18\x03 \x01(\x01\x12\x0e\n\x06median\x18\x04 \x01(\x01\x12\x12\n\npercentile\x18\x05 \x03(\x01\x1aG\n\tDateStats\x12\x0b\n\x03min\x18\x01 \x01(\t\x12\x0b\n\x03max\x18\x02 \x01(\t\x12\x0c\n\x04mean\x18\x03 \x01(\t\x12\x12\n\npercentile\x18\x05 \x03(\t\x1a\x39\n\x10\x43\x61tegoricalStats\x12\x0e\n\x06unique\x18\x01 \x01(\x05\x12\x15\n\rmost_frequent\x18\x02 \x01(\tB\x07\n\x05stats*`\n\tFieldType\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x0b\n\x07INTEGER\x10\x01\x12\x0f\n\x0bREAL_NUMBER\x10\x02\x12\x0f\n\x0b\x43\x41TEGORICAL\x10\x03\x12\x08\n\x04\x44\x41TE\x10\x04\x12\x08\n\x04TEXT\x10\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_FIELDTYPE = _descriptor.EnumDescriptor(
  name='FieldType',
  full_name='FieldType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTEGER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REAL_NUMBER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CATEGORICAL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=643,
  serialized_end=739,
)
_sym_db.RegisterEnumDescriptor(_FIELDTYPE)

FieldType = enum_type_wrapper.EnumTypeWrapper(_FIELDTYPE)
TYPE_UNKNOWN = 0
INTEGER = 1
REAL_NUMBER = 2
CATEGORICAL = 3
DATE = 4
TEXT = 5



_FIELDINFO_INTEGERSTATS = _descriptor.Descriptor(
  name='IntegerStats',
  full_name='FieldInfo.IntegerStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='FieldInfo.IntegerStats.min', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='FieldInfo.IntegerStats.max', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean', full_name='FieldInfo.IntegerStats.mean', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='median', full_name='FieldInfo.IntegerStats.median', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='percentile', full_name='FieldInfo.IntegerStats.percentile', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=405,
)

_FIELDINFO_REALNUMBERSTATS = _descriptor.Descriptor(
  name='RealNumberStats',
  full_name='FieldInfo.RealNumberStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='FieldInfo.RealNumberStats.min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='FieldInfo.RealNumberStats.max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean', full_name='FieldInfo.RealNumberStats.mean', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='median', full_name='FieldInfo.RealNumberStats.median', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='percentile', full_name='FieldInfo.RealNumberStats.percentile', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=500,
)

_FIELDINFO_DATESTATS = _descriptor.Descriptor(
  name='DateStats',
  full_name='FieldInfo.DateStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='FieldInfo.DateStats.min', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='FieldInfo.DateStats.max', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean', full_name='FieldInfo.DateStats.mean', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='percentile', full_name='FieldInfo.DateStats.percentile', index=3,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=573,
)

_FIELDINFO_CATEGORICALSTATS = _descriptor.Descriptor(
  name='CategoricalStats',
  full_name='FieldInfo.CategoricalStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique', full_name='FieldInfo.CategoricalStats.unique', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='most_frequent', full_name='FieldInfo.CategoricalStats.most_frequent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=632,
)

_FIELDINFO = _descriptor.Descriptor(
  name='FieldInfo',
  full_name='FieldInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FieldInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='FieldInfo.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='empty_count', full_name='FieldInfo.empty_count', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='FieldInfo.count', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integer_stats', full_name='FieldInfo.integer_stats', index=4,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real_number_stats', full_name='FieldInfo.real_number_stats', index=5,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_stats', full_name='FieldInfo.date_stats', index=6,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='categorical_stats', full_name='FieldInfo.categorical_stats', index=7,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FIELDINFO_INTEGERSTATS, _FIELDINFO_REALNUMBERSTATS, _FIELDINFO_DATESTATS, _FIELDINFO_CATEGORICALSTATS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='stats', full_name='FieldInfo.stats',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=17,
  serialized_end=641,
)

_FIELDINFO_INTEGERSTATS.containing_type = _FIELDINFO
_FIELDINFO_REALNUMBERSTATS.containing_type = _FIELDINFO
_FIELDINFO_DATESTATS.containing_type = _FIELDINFO
_FIELDINFO_CATEGORICALSTATS.containing_type = _FIELDINFO
_FIELDINFO.fields_by_name['type'].enum_type = _FIELDTYPE
_FIELDINFO.fields_by_name['integer_stats'].message_type = _FIELDINFO_INTEGERSTATS
_FIELDINFO.fields_by_name['real_number_stats'].message_type = _FIELDINFO_REALNUMBERSTATS
_FIELDINFO.fields_by_name['date_stats'].message_type = _FIELDINFO_DATESTATS
_FIELDINFO.fields_by_name['categorical_stats'].message_type = _FIELDINFO_CATEGORICALSTATS
_FIELDINFO.oneofs_by_name['stats'].fields.append(
  _FIELDINFO.fields_by_name['integer_stats'])
_FIELDINFO.fields_by_name['integer_stats'].containing_oneof = _FIELDINFO.oneofs_by_name['stats']
_FIELDINFO.oneofs_by_name['stats'].fields.append(
  _FIELDINFO.fields_by_name['real_number_stats'])
_FIELDINFO.fields_by_name['real_number_stats'].containing_oneof = _FIELDINFO.oneofs_by_name['stats']
_FIELDINFO.oneofs_by_name['stats'].fields.append(
  _FIELDINFO.fields_by_name['date_stats'])
_FIELDINFO.fields_by_name['date_stats'].containing_oneof = _FIELDINFO.oneofs_by_name['stats']
_FIELDINFO.oneofs_by_name['stats'].fields.append(
  _FIELDINFO.fields_by_name['categorical_stats'])
_FIELDINFO.fields_by_name['categorical_stats'].containing_oneof = _FIELDINFO.oneofs_by_name['stats']
DESCRIPTOR.message_types_by_name['FieldInfo'] = _FIELDINFO
DESCRIPTOR.enum_types_by_name['FieldType'] = _FIELDTYPE

FieldInfo = _reflection.GeneratedProtocolMessageType('FieldInfo', (_message.Message,), dict(

  IntegerStats = _reflection.GeneratedProtocolMessageType('IntegerStats', (_message.Message,), dict(
    DESCRIPTOR = _FIELDINFO_INTEGERSTATS,
    __module__ = 'nested_pb2'
    # @@protoc_insertion_point(class_scope:FieldInfo.IntegerStats)
    ))
  ,

  RealNumberStats = _reflection.GeneratedProtocolMessageType('RealNumberStats', (_message.Message,), dict(
    DESCRIPTOR = _FIELDINFO_REALNUMBERSTATS,
    __module__ = 'nested_pb2'
    # @@protoc_insertion_point(class_scope:FieldInfo.RealNumberStats)
    ))
  ,

  DateStats = _reflection.GeneratedProtocolMessageType('DateStats', (_message.Message,), dict(
    DESCRIPTOR = _FIELDINFO_DATESTATS,
    __module__ = 'nested_pb2'
    # @@protoc_insertion_point(class_scope:FieldInfo.DateStats)
    ))
  ,

  CategoricalStats = _reflection.GeneratedProtocolMessageType('CategoricalStats', (_message.Message,), dict(
    DESCRIPTOR = _FIELDINFO_CATEGORICALSTATS,
    __module__ = 'nested_pb2'
    # @@protoc_insertion_point(class_scope:FieldInfo.CategoricalStats)
    ))
  ,
  DESCRIPTOR = _FIELDINFO,
  __module__ = 'nested_pb2'
  # @@protoc_insertion_point(class_scope:FieldInfo)
  ))
_sym_db.RegisterMessage(FieldInfo)
_sym_db.RegisterMessage(FieldInfo.IntegerStats)
_sym_db.RegisterMessage(FieldInfo.RealNumberStats)
_sym_db.RegisterMessage(FieldInfo.DateStats)
_sym_db.RegisterMessage(FieldInfo.CategoricalStats)


# @@protoc_insertion_point(module_scope)
